/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bgslibrary_BgsLib */

#ifndef _Included_bgslibrary_BgsLib
#define _Included_bgslibrary_BgsLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bgslibrary_BgsLib
 * Method:    constructObject
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_bgslibrary_BgsLib_constructObject
  (JNIEnv *, jclass, jstring);

/*
 * Class:     bgslibrary_BgsLib
 * Method:    computeForegroundMask
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_bgslibrary_BgsLib_computeForegroundMask
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     bgslibrary_BgsLib
 * Method:    destroyObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_bgslibrary_BgsLib_destroyObject
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
