#pragma once

#include "IBGS.h"
#include "ILoadSaveConfig.h"

#include "FrameDifference.h"
#include "StaticFrameDifference.h"
#include "WeightedMovingMean.h"
#include "WeightedMovingVariance.h"
#include "MixtureOfGaussianV1.h" // Only for OpenCV == 2
#include "MixtureOfGaussianV2.h"
#include "AdaptiveBackgroundLearning.h"
#include "AdaptiveSelectiveBackgroundLearning.h"
#include "KNN.h" // Only for OpenCV >= 3
#include "GMG.h" // Only for OpenCV >= 2.4.3
#include "DPAdaptiveMedian.h"
#include "DPGrimsonGMM.h"
#include "DPZivkovicAGMM.h"
#include "DPMean.h"
#include "DPWrenGA.h"
#include "DPPratiMediod.h"
#include "DPEigenbackground.h"
#include "DPTexture.h"
#include "T2FGMM_UM.h"
#include "T2FGMM_UV.h"
#include "T2FMRF_UM.h"
#include "T2FMRF_UV.h"
#include "FuzzySugenoIntegral.h"
#include "FuzzyChoquetIntegral.h"
#include "LBSimpleGaussian.h"
#include "LBFuzzyGaussian.h"
#include "LBMixtureOfGaussians.h"
#include "LBAdaptiveSOM.h"
#include "LBFuzzyAdaptiveSOM.h"
#include "LBP_MRF.h"
#include "MultiLayer.h"
#include "PixelBasedAdaptiveSegmenter.h"
#include "VuMeter.h"
#include "KDE.h"
#include "IndependentMultimodal.h"
#include "MultiCue.h"
#include "SigmaDelta.h"
#include "SuBSENSE.h"
#include "LOBSTER.h"
#include "PAWCS.h"
#include "TwoPoints.h"
#include "ViBe.h"
#include "CodeBook.h"

//#include "_template_/MyBGS.h"
//#include "_template_/Amber.h"

using namespace bgslibrary::algorithms;
